name: testplugin
main: com.kittykonnection.com.testplugin.testplugin
version: 1.0

commands:
  moo:
    description: Light yourself on fire for 10 seconds.
    usage: /<command>
    permission: testplugin.moo
    permission-message: You don't have <permission>
  flame:
    description: Light target on fire for 5 seconds.
    usage: /<command> [player]
    permission: testplugin.flame
    permission-message: You don't have <permission>
    